services:
  api:
    image: ${DOCKER_USER:-tu_usuario}/todo-api:latest
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: passwordd
      DB_NAME: todo_db
      PORT: 3000
    networks:
      - todo-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  client:
    image: ${DOCKER_USER:-tu_usuario}/todo-client:latest
    ports:
      - "80:80"
    networks:
      - todo-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  todo-network:
    driver: overlay
